file:
  description: Archive the file
  fields:
    file:
      description: File to be added to the archive
      example: '/config/snapshot.jpg'
    target:
      description: Folder to be used for the archive
      example: '/config/old/'
    name:
      description: Name of the archive. Default name is UTC time
      example: 'old_files'
files_in_folder:
  description: Archive files within the folder, where files are older then defined period of time
  fields:
    folder:
      description: Folder to be scanned for the files
      example: '/config/snapshots'
    time:
      description: Threshold for how old files are (in seconds). Default is 3600 seconds.
      example: 86400
    only_extensions:
      description: List of extensions that are allowed to be archived. Cannot be combined with except_extensions.
      example: '.png'
    except_extensions:
      description: List of extensions that are not allowed to be archived. Cannot be combined with only_extensions.
      example: '.zip'
    target:
      description: Folder to be used for the archive
      example: '/config/old/'
    name:
      description: Name of the archive. Default name is UTC time
      example: 'old_files'